import {useRef,useState} from 'react'
import DrawingCanvas,{type DrawTool,type Stroke} from './DrawingCanvas'
import ArtworkLayer,{type ArtworkItem} from './ArtworkLayer'
import {DEFAULT_LAYERS,SHOE_VIEWS,VIEW_LABELS,downloadProject,isProjectFile,loadLocal,makeProject,saveLocal,type LayerId,type LayerState,type ProjectFile,type ShoeView,type ViewDocument} from './project'
import {initialColors,panelLabels,panelPaths,type PanelColors,type PanelId} from './shoeTemplate'
type Mode='panels'|'draw'|'image'|'layers'|'project';const panelOrder=Object.keys(panelLabels) as PanelId[]
const freshView=():ViewDocument=>({colors:{...initialColors},artworks:[],strokes:[]})
const freshViews=():Record<ShoeView,ViewDocument>=>({outer:freshView(),inner:freshView(),top:freshView(),front:freshView(),heel:freshView()})
function SneakerSvg({view,colors,selected,onSelect,enabled}:{view:ShoeView;colors:PanelColors;selected:PanelId;onSelect:(p:PanelId)=>void;enabled:boolean}){
 const transform=view==='inner'?'translate(845 0) scale(-1 1)':view==='top'?'translate(110 -185) rotate(90 365 230) scale(.78)':view==='front'?'translate(50 -5) scale(.95 1)':view==='heel'?'translate(-20 0) scale(.92 1)':''
 const opacity=(id:PanelId)=>view==='front'&&!['toeBox','toeGuard','tongue','midsole','outsole'].includes(id)?.18:view==='heel'&&!['heel','collar','midsole','outsole'].includes(id)?.18:1
 return <svg className="shoe-svg" viewBox="55 55 735 350"><g transform={transform}><g className="shoe-shadow"><ellipse cx="430" cy="380" rx="310" ry="12"/></g>{(Object.keys(panelPaths) as PanelId[]).map(id=><path key={id} d={panelPaths[id]} fill={colors[id]} opacity={opacity(id)} className={'shoe-panel'+(selected===id&&enabled?' selected':'')} onClick={()=>enabled&&onSelect(id)}/>)}</g></svg>
}
export default function App(){
 const [mode,setMode]=useState<Mode>('panels'),[activeView,setActiveView]=useState<ShoeView>('outer'),[views,setViews]=useState<Record<ShoeView,ViewDocument>>(freshViews),[selected,setSelected]=useState<PanelId>('quarter')
 const [tool,setTool]=useState<DrawTool>('brush'),[drawColor,setDrawColor]=useState('#111111'),[brushSize,setBrushSize]=useState(10),[drawOpacity,setDrawOpacity]=useState(1),[strokeRedo,setStrokeRedo]=useState<Record<ShoeView,Stroke[]>>({outer:[],inner:[],top:[],front:[],heel:[]})
 const [selectedArtwork,setSelectedArtwork]=useState<string|null>(null),[layers,setLayers]=useState<LayerState[]>(DEFAULT_LAYERS),[projectName,setProjectName]=useState('My Sneaker Design'),[status,setStatus]=useState('Not saved yet'),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0})
 const panRef=useRef<{x:number;y:number;px:number;py:number}|null>(null),fileRef=useRef<HTMLInputElement>(null),projectRef=useRef<HTMLInputElement>(null)
 const doc=views[activeView],currentArtwork=doc.artworks.find(x=>x.id===selectedArtwork)??null,visible=(id:LayerId)=>layers.find(x=>x.id===id)?.visible!==false
 const patchView=(patch:Partial<ViewDocument>)=>setViews(v=>({...v,[activeView]:{...v[activeView],...patch}}))
 const changeView=(v:ShoeView)=>{setActiveView(v);setSelectedArtwork(null);setPan({x:0,y:0});setZoom(1)}
 const updateArtwork=(id:string,patch:Partial<ArtworkItem>)=>patchView({artworks:doc.artworks.map(a=>a.id===id?{...a,...patch}:a)})
 const addImage=(f:File)=>{if(!f.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{const id=crypto.randomUUID(),item:ArtworkItem={id,src:String(r.result),name:f.name,x:50,y:50,scale:1,rotation:0,opacity:1};patchView({artworks:[...doc.artworks,item]});setSelectedArtwork(id);setMode('image')};r.readAsDataURL(f)}
 const snapshot=()=>makeProject(projectName,activeView,views,layers),applyProject=(p:ProjectFile)=>{setProjectName(p.name);setViews(p.views);setLayers(p.layers);setActiveView(p.activeView);setSelectedArtwork(null);setStatus('Loaded '+new Date().toLocaleTimeString())}
 const moveLayer=(i:number,d:-1|1)=>{const t=i+d;if(t<0||t>=layers.length)return;setLayers(x=>{const n=[...x];[n[i],n[t]]=[n[t],n[i]];return n})}
 return <main className="app-shell"><header><p className="eyebrow">PHASE 1G · DEDICATED SHOE VIEWS</p><h1>Sneaker Design Studio</h1><p>Dedicated multi-angle shoe templates are being introduced while preserving independent artwork and color data for every view.</p></header>
 <nav className="view-tabs">{SHOE_VIEWS.map(v=><button key={v} className={activeView===v?'active':''} onClick={()=>changeView(v)}><span>{VIEW_LABELS[v]}</span><small>{views[v].artworks.length+views[v].strokes.length} art</small></button>)}</nav>
 <nav className="mode-tabs">{([['panels','▧ Panel'],['draw','✎ Freehand'],['image','▣ Images'],['layers','☷ Layers'],['project','⌁ Project']] as [Mode,string][]).map(([m,l])=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{l}</button>)}</nav>
 <section className="workspace"><div className="canvas-card"><div className="canvas-bar"><span className="view-label">{VIEW_LABELS[activeView].toUpperCase()} · CLASSIC LOW-TOP</span><div className="zoom-controls"><button onClick={()=>setZoom(z=>Math.max(.6,z-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(2.5,z+.1))}>+</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0})}}>Fit</button></div></div>
 <div className="viewport" onPointerDown={e=>{if(e.button!==1&&!e.shiftKey)return;panRef.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(panRef.current)setPan({x:panRef.current.px+e.clientX-panRef.current.x,y:panRef.current.py+e.clientY-panRef.current.y})}} onPointerUp={()=>panRef.current=null}><div className="design-stage" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}><div className={visible('base')?'':'layer-hidden'}><SneakerSvg view={activeView} colors={doc.colors} selected={selected} onSelect={setSelected} enabled={mode==='panels'}/></div><div className={visible('artwork')?'':'layer-hidden'}><ArtworkLayer items={doc.artworks} selectedId={mode==='image'?selectedArtwork:null} onSelect={setSelectedArtwork} onChange={updateArtwork}/></div><div className={'draw-layer '+(mode==='draw'?'enabled':'disabled')+(visible('freehand')?'':' layer-hidden')}><DrawingCanvas tool={tool} color={drawColor} size={brushSize} opacity={drawOpacity} strokes={doc.strokes} onCommit={s=>{patchView({strokes:[...doc.strokes,s]});setStrokeRedo(x=>({...x,[activeView]:[]}))}}/></div></div></div><p className="hint">{VIEW_LABELS[activeView]} view · changes stay with this view · Shift + drag to pan.</p></div>
 <aside><div className="aside-inner">{mode==='panels'&&<><span className="micro">{VIEW_LABELS[activeView].toUpperCase()} · SELECTED PANEL</span><h2>{panelLabels[selected]}</h2><label className="control-row">Fill color<input type="color" value={doc.colors[selected]} onChange={e=>patchView({colors:{...doc.colors,[selected]:e.target.value}})}/></label><code>{doc.colors[selected].toUpperCase()}</code><div className="panel-list">{panelOrder.map(p=><button key={p} className={selected===p?'active':''} onClick={()=>setSelected(p)}>{panelLabels[p]}<span className="mini-swatch" style={{background:doc.colors[p]}}/></button>)}</div></>}
 {mode==='draw'&&<><span className="micro">{VIEW_LABELS[activeView].toUpperCase()} · FREEHAND</span><h2>Paint layer</h2><div className="tool-grid">{(['brush','airbrush','eraser'] as DrawTool[]).map(t=><button key={t} className={tool===t?'active':''} onClick={()=>setTool(t)}>{t}</button>)}</div><label className="control-row">Paint color<input type="color" value={drawColor} onChange={e=>setDrawColor(e.target.value)}/></label><label className="slider-label">Size <b>{brushSize}px</b><input type="range" min="2" max="60" value={brushSize} onChange={e=>setBrushSize(+e.target.value)}/></label><label className="slider-label">Opacity <b>{Math.round(drawOpacity*100)}%</b><input type="range" min="10" max="100" value={drawOpacity*100} onChange={e=>setDrawOpacity(+e.target.value/100)}/></label><div className="history-row"><button disabled={!doc.strokes.length} onClick={()=>{const s=doc.strokes.at(-1);if(s){patchView({strokes:doc.strokes.slice(0,-1)});setStrokeRedo(x=>({...x,[activeView]:[s,...x[activeView]]}))}}}>↶ Stroke</button><button disabled={!strokeRedo[activeView].length} onClick={()=>{const s=strokeRedo[activeView][0];patchView({strokes:[...doc.strokes,s]});setStrokeRedo(x=>({...x,[activeView]:x[activeView].slice(1)}))}}>↷ Stroke</button></div><p className="side-note">{doc.strokes.length} stroke{doc.strokes.length===1?'':'s'} on this view.</p></>}
 {mode==='image'&&<><span className="micro">{VIEW_LABELS[activeView].toUpperCase()} · ARTWORK</span><h2>Images</h2><input ref={fileRef} className="file-input" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)addImage(f);e.target.value=''}}/><button className="primary" onClick={()=>fileRef.current?.click()}>+ Upload image</button><div className="artwork-list">{doc.artworks.map(a=><button key={a.id} className={selectedArtwork===a.id?'active':''} onClick={()=>setSelectedArtwork(a.id)}>{a.name}</button>)}</div>{currentArtwork&&<><label className="slider-label">Size <b>{Math.round(currentArtwork.scale*100)}%</b><input type="range" min="20" max="250" value={currentArtwork.scale*100} onChange={e=>updateArtwork(currentArtwork.id,{scale:+e.target.value/100})}/></label><label className="slider-label">Rotation <b>{currentArtwork.rotation}°</b><input type="range" min="-180" max="180" value={currentArtwork.rotation} onChange={e=>updateArtwork(currentArtwork.id,{rotation:+e.target.value})}/></label><button className="danger" onClick={()=>{patchView({artworks:doc.artworks.filter(a=>a.id!==currentArtwork.id)});setSelectedArtwork(null)}}>Remove image</button></>}</>}
 {mode==='layers'&&<><span className="micro">GLOBAL LAYER MANAGER</span><h2>Design layers</h2><p className="side-note">Visibility and names apply across all five views; artwork content remains view-specific.</p><div className="layer-list">{layers.map((l,i)=><div className="layer-row" key={l.id}><button className="eye" onClick={()=>setLayers(x=>x.map(v=>v.id===l.id?{...v,visible:!v.visible}:v))}>{l.visible?'◉':'○'}</button><input value={l.name} onChange={e=>setLayers(x=>x.map(v=>v.id===l.id?{...v,name:e.target.value}:v))}/><button disabled={!i} onClick={()=>moveLayer(i,-1)}>↑</button><button disabled={i===layers.length-1} onClick={()=>moveLayer(i,1)}>↓</button></div>)}</div></>}
 {mode==='project'&&<><span className="micro">PORTABLE PROJECT V3</span><h2>Five-view project</h2><label className="project-name">Project name<input value={projectName} onChange={e=>setProjectName(e.target.value)}/></label><button className="primary" onClick={()=>{try{saveLocal(snapshot());setStatus('Saved all 5 views locally')}catch{setStatus('Local save failed — download instead')}}}>Save locally</button><button className="reset" onClick={()=>{const p=loadLocal();p?applyProject(p):setStatus('No compatible v3 save found')}}>Load local save</button><button className="reset" onClick={()=>downloadProject(snapshot())}>Download .shoeproject</button><input ref={projectRef} className="file-input" type="file" accept=".shoeproject,application/json" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p:unknown=JSON.parse(String(r.result));isProjectFile(p)?applyProject(p):setStatus('Invalid or older project file')}catch{setStatus('Could not read project')}};r.readAsText(f);e.target.value=''}}/><button className="reset" onClick={()=>projectRef.current?.click()}>Import .shoeproject</button><p className="save-status">{status}</p><div className="view-summary">{SHOE_VIEWS.map(v=><span key={v}>{VIEW_LABELS[v]} <b>{views[v].artworks.length} img · {views[v].strokes.length} strokes</b></span>)}</div></>}</div></aside></section>
 <section className="roadmap"><strong>Phase 1F:</strong> Outer · Inner · Top · Front/Toe · Heel document views, each with independent colors, images, and freehand strokes. All five views save in <strong>.shoeproject v3</strong>.<br/><strong>Prototype note:</strong> view transforms are structural placeholders; dedicated anatomically correct SVG templates come next.</section></main>
}