import {useRef,useState} from 'react'
import ThreeDPreview from './ThreeDPreview'
import OpenSource3DPreview from './OpenSource3DPreview'
import SneakerReferences from './SneakerReferences'
import RealShoe2D from './RealShoe2D'
import DrawingCanvas,{type DrawTool,type Stroke} from './DrawingCanvas'
import ArtworkLayer,{type ArtworkItem} from './ArtworkLayer'
import {DEFAULT_LAYERS,SHOE_VIEWS,VIEW_LABELS,downloadProject,isProjectFile,loadLocal,makeProject,saveLocal,type LayerId,type LayerState,type ProjectFile,type ShoeView,type ViewDocument} from './project'
import {initialColors,panelLabels,type PanelColors,type PanelId} from './shoeTemplate'
import {DEFAULT_SHOE_MODEL_ID,SHOE_MODELS,getShoeModel,modelPanels} from './shoeModels'
import {manifestForModel,partForPanel,partsForView} from './modelManifest'
type Mode='panels'|'draw'|'image'|'layers'|'project';const panelOrder=Object.keys(panelLabels) as PanelId[]
const freshView=():ViewDocument=>({colors:{...initialColors},artworks:[],strokes:[]})
const freshViews=():Record<ShoeView,ViewDocument>=>({outer:freshView(),inner:freshView(),top:freshView(),front:freshView(),heel:freshView()})
export default function App(){
 const [modelId,setModelId]=useState(DEFAULT_SHOE_MODEL_ID),model=getShoeModel(modelId)
 const [referenceImages,setReferenceImages]=useState<Record<string,string>>({})
 const referenceInput=useRef<HTMLInputElement>(null)
 const [useThreeRenderer,setUseThreeRenderer]=useState(false)
 const [show3D,setShow3D]=useState(false),[showReferences,setShowReferences]=useState(false),[real2D,setReal2D]=useState(true)
 const [mode,setMode]=useState<Mode>('panels'),[activeView,setActiveView]=useState<ShoeView>('outer'),[views,setViews]=useState<Record<ShoeView,ViewDocument>>(freshViews),[selected,setSelected]=useState<PanelId>('quarter')
 const [tool,setTool]=useState<DrawTool>('brush'),[drawColor,setDrawColor]=useState('#111111'),[brushSize,setBrushSize]=useState(10),[drawOpacity,setDrawOpacity]=useState(1),[drawClipPanel,setDrawClipPanel]=useState<PanelId|null>(null),[material,setMaterial]=useState<'solid'|'pearl'|'metallic'|'interference'|'chameleon'>('solid'),[strokeRedo,setStrokeRedo]=useState<Record<ShoeView,Stroke[]>>({outer:[],inner:[],top:[],front:[],heel:[]})
 const [selectedArtwork,setSelectedArtwork]=useState<string|null>(null),[layers,setLayers]=useState<LayerState[]>(DEFAULT_LAYERS),[projectName,setProjectName]=useState('My Sneaker Design'),[status,setStatus]=useState('Not saved yet'),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0})
 const panRef=useRef<{x:number;y:number;px:number;py:number}|null>(null),fileRef=useRef<HTMLInputElement>(null),projectRef=useRef<HTMLInputElement>(null)
 const referenceKey=modelId+'|'+activeView
 const referenceImage=referenceImages[referenceKey]
 const modelManifest=manifestForModel(modelId),selectedPart=partForPanel(modelId,selected),viewParts=partsForView(modelId,activeView)
 const doc=views[activeView],currentArtwork=doc.artworks.find(x=>x.id===selectedArtwork)??null,visible=(id:LayerId)=>layers.find(x=>x.id===id)?.visible!==false
 const patchView=(patch:Partial<ViewDocument>)=>setViews(v=>({...v,[activeView]:{...v[activeView],...patch}}))
 const changeView=(v:ShoeView)=>{setActiveView(v);{const p=modelPanels(model,v);if(!p.includes(selected))setSelected(p[0])}setSelectedArtwork(null);setPan({x:0,y:0});setZoom(1)}
 const updateArtwork=(id:string,patch:Partial<ArtworkItem>)=>patchView({artworks:doc.artworks.map(a=>a.id===id?{...a,...patch}:a)})
 const addReferenceImage=(f:File)=>{if(!['image/png','image/jpeg','image/webp','image/svg+xml'].includes(f.type))return;const key=referenceKey;const reader=new FileReader();reader.onload=()=>setReferenceImages(v=>({...v,[key]:String(reader.result)}));reader.readAsDataURL(f)}
 const addImage=(f:File)=>{if(!f.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{const id=crypto.randomUUID(),item:ArtworkItem={id,src:String(r.result),name:f.name,x:50,y:50,scale:1,rotation:0,opacity:1};patchView({artworks:[...doc.artworks,item]});setSelectedArtwork(id);setMode('image')};r.readAsDataURL(f)}
 const snapshot=()=>makeProject(projectName,modelId,activeView,views,layers),applyProject=(p:ProjectFile)=>{const next=getShoeModel(p.modelId);setModelId(next.id);setProjectName(p.name);setViews(p.views);setLayers(p.layers);setActiveView(p.activeView);const panels=modelPanels(next,p.activeView);setSelected(panels[0]);setSelectedArtwork(null);setZoom(1);setPan({x:0,y:0});setStatus('Loaded '+next.name+' · '+new Date().toLocaleTimeString())}
 const moveLayer=(i:number,d:-1|1)=>{const t=i+d;if(t<0||t>=layers.length)return;setLayers(x=>{const n=[...x];[n[i],n[t]]=[n[t],n[i]];return n})}
 return <main className="app-shell"><header><p className="eyebrow">PHASE 1Y.1 · LEGACY 2D REMOVED</p><h1>Sneaker Design Studio</h1><p>Legacy hand-drawn sneaker artwork has been removed from the 2D canvas. Use the real-shoe view or a real PNG/SVG shoe template; the editor no longer falls back to the fake sneaker.</p></header>
 <section className="model-picker"><label>Shoe model<select value={modelId} onChange={e=>{const id=e.target.value,next=getShoeModel(id);setModelId(id);setViews(freshViews());setSelected(modelPanels(next,'outer')[0]);setActiveView('outer');setSelectedArtwork(null);setZoom(1);setPan({x:0,y:0});setStatus('Started '+next.name)}}>{Object.values(SHOE_MODELS).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><span>{model.category} · {model.fidelity} · template v{model.version}</span></section>
 <nav className="view-tabs">{SHOE_VIEWS.map(v=><button key={v} className={activeView===v?'active':''} onClick={()=>changeView(v)}><span>{VIEW_LABELS[v]}</span><small>{views[v].artworks.length+views[v].strokes.length} art</small></button>)}</nav>
 <div className="preview-toggle"><button className={real2D&&!show3D?'active':''} onClick={()=>{setShow3D(false);setReal2D(true)}}>Real 2D</button><button onClick={()=>setShowReferences(v=>!v)}>{showReferences?"Hide real shoe references":"View real sneaker models"}</button><button className={!show3D?'active':''} onClick={()=>setShow3D(false)}>✎ 2D Design</button><button className={show3D?'active':''} onClick={()=>setShow3D(true)}>◈ 3D Preview</button><button className={useThreeRenderer?'active':''} onClick={()=>{setShow3D(true);setUseThreeRenderer(v=>!v)}}>{useThreeRenderer?'Three.js: ON':'Three.js: OFF'}</button></div>
 <div className="reference-tools"><input ref={referenceInput} type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" style={{display:'none'}} onChange={e=>{const f=e.target.files?.[0];if(f)addReferenceImage(f);e.target.value=''}}/><button onClick={()=>{setShow3D(false);setReal2D(false);referenceInput.current?.click()}}>Upload real shoe 2D template ({VIEW_LABELS[activeView]})</button>{referenceImage&&<button onClick={()=>setReferenceImages(v=>{const n={...v};delete n[referenceKey];return n})}>Remove template</button>}<small>Use your own shoe photos or licensed PNG/SVG views. Artwork stays editable above the reference.</small></div><nav className="mode-tabs">{([['panels','▧ Panel'],['draw','✎ Freehand'],['image','▣ Images'],['layers','☷ Layers'],['project','⌁ Project']] as [Mode,string][]).map(([m,l])=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{l}</button>)}</nav>
 {showReferences&&<SneakerReferences/>}
 <section className="workspace"><div className="canvas-card"><div className="canvas-bar"><span className="view-label">{VIEW_LABELS[activeView].toUpperCase()} · {model.name.toUpperCase()}</span><div className="zoom-controls"><button onClick={()=>setZoom(z=>Math.max(.6,z-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(2.5,z+.1))}>+</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0})}}>Fit</button></div></div>
 {show3D&&useThreeRenderer?<OpenSource3DPreview modelId={modelId} colors={doc.colors} selected={selected} material={material} onSelect={p=>{setSelected(p);setMode('panels')}}/>:show3D?<ThreeDPreview modelId={modelId} colors={doc.colors} selected={selected} material={material} onMaterialChange={setMaterial} onSelect={p=>{setSelected(p);setMode('panels')}}/>:real2D&&modelId==='classic-low-top'?<div className="viewport real-reference-viewport"><RealShoe2D view={activeView} colors={doc.colors} selected={selected} onSelect={setSelected} enabled={mode==='panels'}/></div>:<div className="viewport" onPointerDown={e=>{if(e.button!==1&&!e.shiftKey)return;panRef.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(panRef.current)setPan({x:panRef.current.px+e.clientX-panRef.current.x,y:panRef.current.py+e.clientY-panRef.current.y})}} onPointerUp={()=>panRef.current=null}><div className="design-stage" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}><div className={visible('base')?'':'layer-hidden'}>{referenceImage?<img src={referenceImage} alt={model.name+' '+VIEW_LABELS[activeView]+' reference'} className="shoe-reference-image" draggable={false}/>:<div className="real-template-required"><b>No fake shoe fallback</b><span>Upload a real PNG/SVG template for this shoe and view, or choose Real 2D.</span><button onClick={()=>referenceInput.current?.click()}>Upload real shoe template</button></div>}</div><div className={visible('artwork')?'':'layer-hidden'}><ArtworkLayer items={doc.artworks} selectedId={mode==='image'?selectedArtwork:null} onSelect={setSelectedArtwork} onChange={updateArtwork} clipPaths={model.views[activeView].paths} viewBox={model.views[activeView].viewBox} mirror={model.views[activeView].mirror}/></div><div className={'draw-layer '+(mode==='draw'?'enabled':'disabled')+(visible('freehand')?'':' layer-hidden')}><DrawingCanvas tool={tool} color={drawColor} size={brushSize} opacity={drawOpacity} strokes={doc.strokes} clipPanel={drawClipPanel} material={material} clipPaths={model.views[activeView].paths} viewBox={model.views[activeView].viewBox} mirror={model.views[activeView].mirror} onCommit={s=>{patchView({strokes:[...doc.strokes,s]});setStrokeRedo(x=>({...x,[activeView]:[]}))}}/></div></div></div>}<p className="hint">{show3D?"3D preview · choose 2D Design to paint or upload artwork.":"2D "+VIEW_LABELS[activeView]+" view · Shift + drag to pan."}</p></div>
 <aside><div className="aside-inner">{mode==='panels'&&<><span className="micro">{VIEW_LABELS[activeView].toUpperCase()} · SELECTED PANEL</span><h2>{panelLabels[selected]}</h2><label className="control-row">Fill color<input type="color" value={doc.colors[selected]} onChange={e=>patchView({colors:{...doc.colors,[selected]:e.target.value}})}/></label><code>{doc.colors[selected].toUpperCase()}</code>{selectedPart&&<div className="model-part-card"><span className="micro">MODEL COMPONENT</span><b>{selectedPart.label}</b><small>{selectedPart.id} · {selectedPart.material} · mesh: {selectedPart.futureMeshName}</small></div>}<div className="panel-list">{modelPanels(model,activeView).map(p=><button key={p} className={selected===p?'active':''} onClick={()=>setSelected(p)}>{panelLabels[p]}<span className="mini-swatch" style={{background:doc.colors[p]}}/></button>)}</div></>}
 {mode==='draw'&&<><span className="micro">{VIEW_LABELS[activeView].toUpperCase()} · FREEHAND</span><h2>Paint layer</h2><div className="tool-grid">{(['brush','airbrush','eraser'] as DrawTool[]).map(t=><button key={t} className={tool===t?'active':''} onClick={()=>setTool(t)}>{t}</button>)}</div><label className="control-row">Paint color<input type="color" value={drawColor} onChange={e=>setDrawColor(e.target.value)}/></label><label className="slider-label">Size <b>{brushSize}px</b><input type="range" min="2" max="60" value={brushSize} onChange={e=>setBrushSize(+e.target.value)}/></label><label className="slider-label">Opacity <b>{Math.round(drawOpacity*100)}%</b><input type="range" min="10" max="100" value={drawOpacity*100} onChange={e=>setDrawOpacity(+e.target.value/100)}/></label><label className="project-name">Material<select value={material} onChange={e=>setMaterial(e.target.value as typeof material)}><option value="solid">Solid</option><option value="pearl">Pearl</option><option value="metallic">Metallic</option><option value="interference">Interference</option><option value="chameleon">Chameleon</option></select></label><label className="project-name">Clip paint<select value={drawClipPanel??''} onChange={e=>setDrawClipPanel((e.target.value||null) as PanelId|null)}><option value="">Free / Unclipped</option>{modelPanels(model,activeView).map(p=><option key={p} value={p}>{panelLabels[p]}</option>)}</select></label><button className="reset" onClick={()=>setDrawClipPanel(selected)}>Clip paint to selected panel: {panelLabels[selected]}</button><div className="history-row"><button disabled={!doc.strokes.length} onClick={()=>{const s=doc.strokes.at(-1);if(s){patchView({strokes:doc.strokes.slice(0,-1)});setStrokeRedo(x=>({...x,[activeView]:[s,...x[activeView]]}))}}}>↶ Stroke</button><button disabled={!strokeRedo[activeView].length} onClick={()=>{const s=strokeRedo[activeView][0];patchView({strokes:[...doc.strokes,s]});setStrokeRedo(x=>({...x,[activeView]:x[activeView].slice(1)}))}}>↷ Stroke</button></div><p className="side-note">{doc.strokes.length} stroke{doc.strokes.length===1?'':'s'} on this view.</p></>}
 {mode==='image'&&<><span className="micro">{VIEW_LABELS[activeView].toUpperCase()} · ARTWORK</span><h2>Images</h2><input ref={fileRef} className="file-input" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)addImage(f);e.target.value=''}}/><button className="primary" onClick={()=>fileRef.current?.click()}>+ Upload image</button><div className="artwork-list">{doc.artworks.map(a=><button key={a.id} className={selectedArtwork===a.id?'active':''} onClick={()=>setSelectedArtwork(a.id)}>{a.name}</button>)}</div>{currentArtwork&&<><label className="slider-label">Size <b>{Math.round(currentArtwork.scale*100)}%</b><input type="range" min="20" max="250" value={currentArtwork.scale*100} onChange={e=>updateArtwork(currentArtwork.id,{scale:+e.target.value/100})}/></label><label className="slider-label">Rotation <b>{currentArtwork.rotation}°</b><input type="range" min="-180" max="180" value={currentArtwork.rotation} onChange={e=>updateArtwork(currentArtwork.id,{rotation:+e.target.value})}/></label><label className="project-name">Clip artwork<select value={currentArtwork.clipPanel??''} onChange={e=>updateArtwork(currentArtwork.id,{clipPanel:(e.target.value||null) as PanelId|null})}><option value="">Free / Unclipped</option>{modelPanels(model,activeView).map(p=><option key={p} value={p}>{panelLabels[p]}</option>)}</select></label><button className="reset" onClick={()=>updateArtwork(currentArtwork.id,{clipPanel:selected})}>Clip to selected panel: {panelLabels[selected]}</button><button className="danger" onClick={()=>{patchView({artworks:doc.artworks.filter(a=>a.id!==currentArtwork.id)});setSelectedArtwork(null)}}>Remove image</button></>}</>}
 {mode==='layers'&&<><span className="micro">GLOBAL LAYER MANAGER</span><h2>Design layers</h2><p className="side-note">Visibility and names apply across all five views; artwork content remains view-specific.</p><div className="layer-list">{layers.map((l,i)=><div className="layer-row" key={l.id}><button className="eye" onClick={()=>setLayers(x=>x.map(v=>v.id===l.id?{...v,visible:!v.visible}:v))}>{l.visible?'◉':'○'}</button><input value={l.name} onChange={e=>setLayers(x=>x.map(v=>v.id===l.id?{...v,name:e.target.value}:v))}/><button disabled={!i} onClick={()=>moveLayer(i,-1)}>↑</button><button disabled={i===layers.length-1} onClick={()=>moveLayer(i,1)}>↓</button></div>)}</div></>}
 {mode==='project'&&<><span className="micro">PORTABLE PROJECT V4</span><h2>Five-view project</h2><label className="project-name">Project name<input value={projectName} onChange={e=>setProjectName(e.target.value)}/></label><button className="primary" onClick={()=>{try{saveLocal(snapshot());setStatus('Saved all 5 views locally')}catch{setStatus('Local save failed — download instead')}}}>Save locally</button><button className="reset" onClick={()=>{const p=loadLocal();p?applyProject(p):setStatus('No compatible v4 save found')}}>Load local save</button><button className="reset" onClick={()=>downloadProject(snapshot())}>Download .shoeproject</button><input ref={projectRef} className="file-input" type="file" accept=".shoeproject,application/json" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p:unknown=JSON.parse(String(r.result));isProjectFile(p)?applyProject(p):setStatus('Invalid or older project file — Phase 1H uses v4')}catch{setStatus('Could not read project')}};r.readAsText(f);e.target.value=''}}/><button className="reset" onClick={()=>projectRef.current?.click()}>Import .shoeproject</button><p className="save-status">{status}</p><div className="view-summary">{SHOE_VIEWS.map(v=><span key={v}>{VIEW_LABELS[v]} <b>{views[v].artworks.length} img · {views[v].strokes.length} strokes</b></span>)}</div></>}</div></aside></section>
 <section className="roadmap"><strong>Phase 1V:</strong> clean real-shoe 2D canvas · direct region selection · hotspot circles removed · vector fallback preserved · fixed production views next.<br/>Classic Low-Top currently exposes <strong>{modelManifest?.parts.length??0}</strong> mapped components; this {VIEW_LABELS[activeView]} view exposes <strong>{viewParts.length}</strong>. Existing 2D painting, clipping, uploaded artwork, layers, and portable projects remain intact.<br/><strong>Asset required:</strong> add an owned or properly licensed sneaker GLB at /public/models/classic-low-top.glb with named meshes matching the component manifest. The app will load the real shoe automatically.</section></main>
}