import { useMemo,useRef,useState } from 'react'
import DrawingCanvas,{type DrawTool,type Stroke} from './DrawingCanvas'
import ArtworkLayer,{type ArtworkItem} from './ArtworkLayer'
import {DEFAULT_LAYERS,downloadProject,isProjectFile,loadLocal,makeProject,saveLocal,type LayerId,type LayerState,type ProjectFile} from './project'
import {initialColors,panelLabels,panelPaths,type PanelColors,type PanelId} from './shoeTemplate'
type Mode='panels'|'draw'|'image'|'layers'|'project';type HistoryState={colors:PanelColors};const panelOrder=Object.keys(panelLabels) as PanelId[]
function SneakerSvg({colors,selected,onSelect,enabled}:{colors:PanelColors;selected:PanelId;onSelect:(p:PanelId)=>void;enabled:boolean}){return <svg className="shoe-svg" viewBox="55 55 735 350"><g className="shoe-shadow"><ellipse cx="430" cy="380" rx="310" ry="12"/></g>{(Object.keys(panelPaths) as PanelId[]).map(id=><path key={id} d={panelPaths[id]} fill={colors[id]} className={'shoe-panel'+(selected===id&&enabled?' selected':'')} onClick={()=>enabled&&onSelect(id)}/>)}<g className="shoe-details"><path d="M328 166 L354 218 M345 158 L370 213 M361 153 L385 207"/><path d="M171 185 C188 176 205 176 222 181 M167 202 C187 194 205 194 224 199"/><path d="M535 184 C573 179 616 186 647 204"/></g></svg>}
export default function App(){
 const [mode,setMode]=useState<Mode>('panels'),[selected,setSelected]=useState<PanelId>('quarter'),[colors,setColors]=useState<PanelColors>({...initialColors}),[past,setPast]=useState<HistoryState[]>([]),[future,setFuture]=useState<HistoryState[]>([])
 const [tool,setTool]=useState<DrawTool>('brush'),[drawColor,setDrawColor]=useState('#111111'),[brushSize,setBrushSize]=useState(10),[drawOpacity,setDrawOpacity]=useState(1),[strokes,setStrokes]=useState<Stroke[]>([]),[strokeRedo,setStrokeRedo]=useState<Stroke[]>([])
 const [artworks,setArtworks]=useState<ArtworkItem[]>([]),[selectedArtwork,setSelectedArtwork]=useState<string|null>(null),[layers,setLayers]=useState<LayerState[]>(DEFAULT_LAYERS),[projectName,setProjectName]=useState('My Sneaker Design'),[status,setStatus]=useState('Not saved yet')
 const [zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0});const panRef=useRef<{x:number;y:number;px:number;py:number}|null>(null),fileRef=useRef<HTMLInputElement>(null),projectRef=useRef<HTMLInputElement>(null)
 const currentArtwork=artworks.find(x=>x.id===selectedArtwork)??null,changedCount=useMemo(()=>panelOrder.filter(id=>colors[id]!==initialColors[id]).length,[colors]),visible=(id:LayerId)=>layers.find(x=>x.id===id)?.visible!==false
 const commitColors=(next:PanelColors)=>{setPast(x=>[...x.slice(-39),{colors:{...colors}}]);setColors(next);setFuture([])},undo=()=>{const p=past.at(-1);if(!p)return;setFuture(x=>[{colors:{...colors}},...x]);setColors({...p.colors});setPast(x=>x.slice(0,-1))},redo=()=>{const n=future[0];if(!n)return;setPast(x=>[...x,{colors:{...colors}}]);setColors({...n.colors});setFuture(x=>x.slice(1))}
 const updateArtwork=(id:string,patch:Partial<ArtworkItem>)=>setArtworks(x=>x.map(a=>a.id===id?{...a,...patch}:a)),addImage=(f:File)=>{if(!f.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{const id=crypto.randomUUID();setArtworks(x=>[...x,{id,src:String(r.result),name:f.name,x:50,y:50,scale:1,rotation:0,opacity:1}]);setSelectedArtwork(id);setMode('image')};r.readAsDataURL(f)}
 const snapshot=()=>makeProject(projectName,colors,artworks,strokes,layers),applyProject=(p:ProjectFile)=>{setProjectName(p.name);setColors(p.colors);setArtworks(p.artworks);setStrokes(p.strokes);setLayers(p.layers);setPast([]);setFuture([]);setStrokeRedo([]);setStatus('Loaded '+new Date().toLocaleTimeString())}
 const save=()=>{try{saveLocal(snapshot());setStatus('Saved locally '+new Date().toLocaleTimeString())}catch{setStatus('Local save failed — download the project instead')}}
 const moveLayer=(i:number,d:-1|1)=>{const t=i+d;if(t<0||t>=layers.length)return;setLayers(x=>{const n=[...x];[n[i],n[t]]=[n[t],n[i]];return n})}
 return <main className="app-shell"><header><p className="eyebrow">PHASE 1E · PERSISTENT DRAWING</p><h1>Sneaker Design Studio</h1><p>Freehand artwork is now stored as vector stroke data so drawings can survive save, export, refresh, and import.</p></header>
 <nav className="mode-tabs">{([['panels','▧ Panel'],['draw','✎ Freehand'],['image','▣ Images'],['layers','☷ Layers'],['project','⌁ Project']] as [Mode,string][]).map(([m,l])=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{l}</button>)}</nav>
 <section className="workspace"><div className="canvas-card"><div className="canvas-bar"><span className="view-label">OUTER SIDE · LOW-TOP PROTOTYPE</span><div className="zoom-controls"><button onClick={()=>setZoom(z=>Math.max(.6,z-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(2.5,z+.1))}>+</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0})}}>Fit</button></div></div>
 <div className="viewport" onPointerDown={e=>{if(e.button!==1&&!e.shiftKey)return;panRef.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(panRef.current)setPan({x:panRef.current.px+e.clientX-panRef.current.x,y:panRef.current.py+e.clientY-panRef.current.y})}} onPointerUp={()=>panRef.current=null}><div className="design-stage" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}><div className={visible('base')?'':'layer-hidden'}><SneakerSvg colors={colors} selected={selected} onSelect={setSelected} enabled={mode==='panels'}/></div><div className={visible('artwork')?'':'layer-hidden'}><ArtworkLayer items={artworks} selectedId={mode==='image'?selectedArtwork:null} onSelect={setSelectedArtwork} onChange={updateArtwork}/></div><div className={'draw-layer '+(mode==='draw'?'enabled':'disabled')+(visible('freehand')?'':' layer-hidden')}><DrawingCanvas tool={tool} color={drawColor} size={brushSize} opacity={drawOpacity} strokes={strokes} onCommit={s=>{setStrokes(x=>[...x,s]);setStrokeRedo([])}}/></div></div></div><p className="hint">Zoom with +/− · Hold Shift and drag to pan.</p></div>
 <aside>{mode==='panels'&&<><span className="micro">SELECTED PANEL</span><h2>{panelLabels[selected]}</h2><label className="control-row">Fill color<input type="color" value={colors[selected]} onChange={e=>e.target.value!==colors[selected]&&commitColors({...colors,[selected]:e.target.value})}/></label><code>{colors[selected].toUpperCase()}</code><div className="panel-list">{panelOrder.map(p=><button key={p} className={selected===p?'active':''} onClick={()=>setSelected(p)}>{panelLabels[p]}<span className="mini-swatch" style={{background:colors[p]}}/></button>)}</div><div className="history-row"><button onClick={undo} disabled={!past.length}>↶ Undo</button><button onClick={redo} disabled={!future.length}>↷ Redo</button></div></>}
 {mode==='draw'&&<><span className="micro">PERSISTENT FREEHAND</span><h2>Paint layer</h2><div className="tool-grid">{(['brush','airbrush','eraser'] as DrawTool[]).map(t=><button key={t} className={tool===t?'active':''} onClick={()=>setTool(t)}>{t}</button>)}</div><label className="control-row">Paint color<input type="color" value={drawColor} onChange={e=>setDrawColor(e.target.value)}/></label><label className="slider-label">Size <b>{brushSize}px</b><input type="range" min="2" max="60" value={brushSize} onChange={e=>setBrushSize(+e.target.value)}/></label><label className="slider-label">Opacity <b>{Math.round(drawOpacity*100)}%</b><input type="range" min="10" max="100" value={drawOpacity*100} onChange={e=>setDrawOpacity(+e.target.value/100)}/></label><div className="history-row"><button disabled={!strokes.length} onClick={()=>{const s=strokes.at(-1);if(s){setStrokes(x=>x.slice(0,-1));setStrokeRedo(x=>[s,...x])}}}>↶ Stroke</button><button disabled={!strokeRedo.length} onClick={()=>{const s=strokeRedo[0];setStrokes(x=>[...x,s]);setStrokeRedo(x=>x.slice(1))}}>↷ Stroke</button></div><button className="reset" disabled={!strokes.length} onClick={()=>{setStrokeRedo([...strokes]);setStrokes([])}}>Clear freehand</button><p className="side-note">{strokes.length} stored vector stroke{strokes.length===1?'':'s'}</p></>}
 {mode==='image'&&<><span className="micro">IMAGE ARTWORK</span><h2>Artwork</h2><input ref={fileRef} className="file-input" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)addImage(f);e.target.value=''}}/><button className="primary" onClick={()=>fileRef.current?.click()}>+ Upload image</button><div className="artwork-list">{artworks.map(a=><button key={a.id} className={selectedArtwork===a.id?'active':''} onClick={()=>setSelectedArtwork(a.id)}>{a.name}</button>)}</div>{currentArtwork&&<><label className="slider-label">Size <b>{Math.round(currentArtwork.scale*100)}%</b><input type="range" min="20" max="250" value={currentArtwork.scale*100} onChange={e=>updateArtwork(currentArtwork.id,{scale:+e.target.value/100})}/></label><label className="slider-label">Rotation <b>{currentArtwork.rotation}°</b><input type="range" min="-180" max="180" value={currentArtwork.rotation} onChange={e=>updateArtwork(currentArtwork.id,{rotation:+e.target.value})}/></label><button className="danger" onClick={()=>{setArtworks(x=>x.filter(a=>a.id!==currentArtwork.id));setSelectedArtwork(null)}}>Remove image</button></>}</>}
 {mode==='layers'&&<><span className="micro">LAYER MANAGER</span><h2>Design layers</h2><div className="layer-list">{layers.map((l,i)=><div className="layer-row" key={l.id}><button className="eye" onClick={()=>setLayers(x=>x.map(v=>v.id===l.id?{...v,visible:!v.visible}:v))}>{l.visible?'◉':'○'}</button><input value={l.name} onChange={e=>setLayers(x=>x.map(v=>v.id===l.id?{...v,name:e.target.value}:v))}/><button disabled={!i} onClick={()=>moveLayer(i,-1)}>↑</button><button disabled={i===layers.length-1} onClick={()=>moveLayer(i,1)}>↓</button></div>)}</div></>}
 {mode==='project'&&<><span className="micro">PORTABLE PROJECT V2</span><h2>Save & transfer</h2><label className="project-name">Project name<input value={projectName} onChange={e=>setProjectName(e.target.value)}/></label><button className="primary" onClick={save}>Save locally</button><button className="reset" onClick={()=>{const p=loadLocal();p?applyProject(p):setStatus('No compatible v2 local save found')}}>Load local save</button><button className="reset" onClick={()=>downloadProject(snapshot())}>Download .shoeproject</button><input ref={projectRef} className="file-input" type="file" accept=".shoeproject,application/json" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p:unknown=JSON.parse(String(r.result));isProjectFile(p)?applyProject(p):setStatus('Invalid or older project file')}catch{setStatus('Could not read project file')}};r.readAsText(f);e.target.value=''}}/><button className="reset" onClick={()=>projectRef.current?.click()}>Import .shoeproject</button><p className="save-status">{status}</p></>}</aside></section>
 <section className="roadmap"><strong>Phase 1E:</strong> persistent vector brush/airbrush strokes · drawing undo/redo · freehand data in local saves and .shoeproject v2 · restored drawings after import.<br/><strong>Next:</strong> multi-view shoe document architecture and proper per-view artwork.</section></main>
}